CREATE TABLE IF NOT EXISTS yellow_taxi_2025 (
    id                      BIGSERIAL,
    VendorID                INTEGER,
    tpep_pickup_datetime    TIMESTAMPTZ,
    tpep_dropoff_datetime   TIMESTAMPTZ,
    passenger_count         FLOAT,
    trip_distance           FLOAT,
    RatecodeID              FLOAT,
    store_and_fwd_flag      VARCHAR(1),
    PULocationID            INTEGER,
    DOLocationID            INTEGER,
    payment_type            BIGINT,
    fare_amount             FLOAT,
    extra                   FLOAT,
    mta_tax                 FLOAT,
    tip_amount              FLOAT,
    tolls_amount            FLOAT,
    improvement_surcharge   FLOAT,
    total_amount            FLOAT,
    congestion_surcharge    FLOAT,
    Airport_fee             FLOAT,
    cbd_congestion_fee      FLOAT
);
